### ISSUE TITLE
SMQ Monitor needs to use relative paths

### ISSUE THREAD

**Issue by chris-elmstone** [weyoss/redis-smq-monitor-client#10]
Hello

We have enabled Redis SMQ Monitor for our project, the issue is as it is behind an Nginx proxy where the port is placed in /queue-monitor route.

When we load though it tries to access the assets via the root of the domain rather than on the specified path.

Is there any way to change this?

Best Regards
Chris

**Comment by weyoss** [comment]
Thank you for opening this issue.

When using RedisSMQ Monitor from behind an nginx proxy you need to properly configure your server to redirect http/websocket requests.

Meanwhile I am going to see if we can update the web ui to use relative paths.

**Comment by weyoss** [comment]
This issue has been resolved in recent releases.

See [Running the Web UI behind a reverse proxy](https://github.com/weyoss/redis-smq/blob/master/docs/web-ui.md#running-the-web-ui-behind-a-reverse-proxy).

**Comment by weyoss** [comment]
Closing as resolved.
