### ISSUE TITLE
Getting issue if I click on Messages link of the monitor screen.

### ISSUE THREAD

**Issue by shahidmau** [weyoss/redis-smq-monitor-client#12]
I am getting the given issue if I click on **Messages** link.
`TypeError: Cannot read properties of undefined (reading 'uuid')`

Full error is given here.
<img width="570" alt="Screenshot 2022-06-28 at 12 37 56 PM" src="https://user-images.githubusercontent.com/195240/176115745-33157828-dc74-4de3-a80c-84da629d0d1b.png">

Attaching the screenshot of the monitor screen.
<img width="1382" alt="Screenshot 2022-06-28 at 12 36 34 PM" src="https://user-images.githubusercontent.com/195240/176115970-3689a035-c23f-4a3c-839e-239d3eea45ff.png">

OS: MacOS Monterey
Node Versions: 14.x and 16.x (tried on these two versions)

Thanks for this awesome library. :)

**Comment by weyoss** [comment]
@shahidmau Thank you for reporting this issue.

This issue is related to [redis-smq-monitor-client](https://github.com/weyoss/redis-smq-monitor-client). 

A quick fix will be published ASAP.

**Comment by weyoss** [comment]
This issue has been fixed in `redis-smq-monitor@7.0.3`.

**Comment by weyoss** [comment]
Closing as resolved.
