### ISSUE TITLE
don't see any chart movements and other metrics

### ISSUE THREAD

**Issue by abhagsain** [weyoss/redis-smq-monitor-client#7]
version - `5.0.0`

Hi, @weyoss 
First of all thanks for building`redis-smq`. Didn't want the overhead of RabbitMQ, or Kafka, and `redis-smq` is perfect for my use case.

The issue is I'm not seeing chart movement and other metrics.
Not sure if I'm doing something wrong. 

The app is inside a docker container and I'm using Nginx as a proxy.

![image](https://user-images.githubusercontent.com/36589645/144877767-58ac86b8-cc15-40b6-b0a2-ac356d81243b.png)

Here's the demo code 

```  
  const config = {
    namespace: "price-service",
    redis: {
      client: RedisClientName.IOREDIS,
      options: { host: "redis-service", port: 6379, url: "redis-service" },
    },
    monitor: {
      enabled: true,
      port: 4003,
    },
  }


const producer = new Producer("test", config);

  producer.produceMessage(new Message().setBody(response), console.log);

   class TestQueueConsumer extends Consumer {
    consume(message, cb) {
      // console.log("Got a message to consume:", message);
      cb();
    }
  }

  const consumer = new TestQueueConsumer("test", config);
  consumer.run()

```

To put data 

```
setInterval(() => {
    for (let i = 0; i < 10000; i++) {
      producer.produceMessage(new Message().setBody({ count: i }), console.log);
    }
  }, 1000)

```

**Comment by abhagsain** [comment]
My bad, There was a version mismatch. Chart is working fine. 
However when I click on the `Acknowledged messages` the server sends `500`

![image](https://user-images.githubusercontent.com/36589645/144894594-d16e5a76-1810-41fa-a2e6-34469a0b1b5f.png)
![image](https://user-images.githubusercontent.com/36589645/144894742-11ec4031-17b5-4da2-bb48-c25e911da924.png)

**Comment by weyoss** [comment]
hey @abhagsain 

I have just checked the Web UI and it is working correctly:

![Screen Shot 2021-12-06 at 21 59 25](https://user-images.githubusercontent.com/25721917/144904440-f2cfff41-d026-40db-aaea-55a641148aeb.png)

I guess you have upgraded your installation from v2 to v5. Major versions can be sometimes incompatible with each other, and that is normal. 

Before upgrading to a major version, as a good practice, you should always clean up your Redis server.

I highly suspect that you have a data incompatibility issue between different versions of RedisSMQ. Please shutdown RedisSMQ (consumers, producers, monitors) and run `redis-cli flushall` from a terminal. If you have any important data, make a backup first.

Also make sure to run the same RedisSMQ version from all your docker containers.

**Comment by abhagsain** [comment]
Hi, @weyoss 

I tried flushing multiple times, ran only producer to see the pending message but still no luck 😢 

![image](https://user-images.githubusercontent.com/36589645/144954549-323e8e73-f362-4754-960d-d285c2b3a5c8.png)
![image](https://user-images.githubusercontent.com/36589645/144954574-89a18f57-e4d6-4a3f-abc4-d40563c0911c.png)

I turned on the logs and got this error. Please take a look

```
{
   "name":"monitor-server",
   "hostname":"258f57eeed6d",
   "pid":140,
   "level":50,
   "err":{
      "message":"(0 , class_transformer_1.plainToClass) is not a function",
      "name":"TypeError",
      "stack":"TypeError: (0 , class_transformer_1.plainToClass) is not a function\n    at /app/price-service/node_modules/redis-smq/src/monitor-server/utils/validate-dto.ts:8:30\n    at Generator.next (<anonymous>)\n    at /app/price-service/node_modules/redis-smq/dist/src/monitor-server/utils/validate-dto.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/price-service/node_modules/redis-smq/dist/src/monitor-server/utils/validate-dto.js:4:12)\n    at validateDTO (/app/price-service/node_modules/redis-smq/dist/src/monitor-server/utils/validate-dto.js:16:12)\n    at /app/price-service/node_modules/redis-smq/src/monitor-server/middlewares/request-validator.ts:30:38\n    at Generator.next (<anonymous>)\n    at /app/price-service/node_modules/redis-smq/dist/src/monitor-server/middlewares/request-validator.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/price-service/node_modules/redis-smq/dist/src/monitor-server/middlewares/request-validator.js:4:12)\n    at /app/price-service/node_modules/redis-smq/src/monitor-server/middlewares/request-validator.ts:10:30\n    at dispatch (/app/price-service/node_modules/koa-compose/index.js:42:32)\n    at /app/price-service/node_modules/@koa/router/lib/router.js:372:16\n    at dispatch (/app/price-service/node_modules/koa-compose/index.js:42:32)\n    at allowedMethods (/app/price-service/node_modules/@koa/router/lib/router.js:433:12)\n    at dispatch (/app/price-service/node_modules/koa-compose/index.js:42:32)\n    at /app/price-service/node_modules/@koa/router/lib/router.js:372:16\n    at dispatch (/app/price-service/node_modules/koa-compose/index.js:42:32)\n    at /app/price-service/node_modules/koa-compose/index.js:34:12\n    at dispatch (/app/price-service/node_modules/@koa/router/lib/router.js:377:31)\n    at dispatch (/app/price-service/node_modules/koa-compose/index.js:42:32)"
   },
   "msg":"(0 , class_transformer_1.plainToClass) is not a function",
   "time":"2021-12-07T02:37:38.062Z",
   "v":0
}
```

**Comment by weyoss** [comment]
@abhagsain 

It is an error coming from `class-transformer` package which is used by `redis-smq`.

RedisSMQ has been tested against `class-transformer@0.4.0` but at the time when you installed `redis-smq` `class-transformer@0.5.0` was downloaded instead of `class-transformer@0.4.0`. This occurred because `package.json` is using `"class-transformer": "^0.4.0"`.

`class-transformer@0.5.0` is faulty. See https://github.com/typestack/class-validator/issues/1411.

I am going to fix this issue ASAP.

**Comment by weyoss** [comment]
This issue has been fixed.

Please upgrade `redis-smq` to the latest version (currently v5.0.11).

**Comment by abhagsain** [comment]
Yes, it's working now 🎊 
You can close this. 

Thank you so much @weyoss

**Comment by weyoss** [comment]
Closing as resolved.
